### ISSUE TITLE
Map isn't rotating after game loss

### ISSUE THREAD

**Issue by Zariaa27** [Resxt/Plutonium-T6-Scripts#4]
Hey! This script is great, but it seems as when someone votes for a map, when the game restarts, 

Here's my cfg
```
set mapvote_enable 1
set mapvote_maps "Bus Depot,Bus Depot,zm_classic_prison:Nuketown,Nuketown,zm_standard_nuked:Origins,Origins,zm_classic_processing:Die Rise,Die Rise"
set mapvote_limits_max 12
set mapvote_colors_selected "blue"
set mapvote_colors_unselected "white"
set mapvote_colors_timer "blue"
set mapvote_colors_timer_low "red"
set mapvote_colors_help_text "white"
set mapvote_colors_help_accent "blue"
set mapvote_colors_help_accent_mode "standard"
set mapvote_vote_time 30
set mapvote_blur_level 2.5
set mapvote_blur_fade_in_time 2
set mapvote_horizontal_spacing 75
set mapvote_display_wait_time 1
set mapvote_default_rotation_enable 0
set mapvote_default_rotation_maps "Bus Depot,Bus Depot,zm_classic_prison:Nuketown,Nuketown,zm_standard_nuked:Origins,Origins,zm_classic_processing:Die Rise,Die Rise"
set mapvote_default_rotation_min_players 0
set mapvote_default_rotation_max_players 0
sv_maprotation "exec zm_classic_rooftop.cfg map zm_highrise exec zm_standard_nuked.cfg map zm_nuked exec zm_standard_transit.cfg map zm_transit exec zm_classic_tomb.cfg map zm_tomb"
```

I tried removing the original maprotation line but when doing so, the server doesn't start.

**Comment by Resxt** [comment]
You need to stick to the information provided. Do not remove the map rotation, otherwise I would have said it in the instructions.

I just tried it with the files from Github with the default mapvote values, on a clean copy of Plutonium (latest version) and it works just fine. The issue is on your side.

Make sure you don't have any conflicting script, make sure that your server works fine without the mapvote first, make sure you installed both of the required files and make sure you pasted the dvars at the right place (or just don't paste them at all).
All dvars go above `sv_maprotation` and most importantly above `map_rotate` in the CFG.

Also use the default values at first to see if the issue does not come from you doing a mistake while editing the maps dvar or whatever and obviously if you want to load a DLC map make sure the DLC is installed on the server and of course the players have to have it too to be able to load onto it, which is not related to the mapvote itself.

![image](https://github.com/Resxt/Plutonium-T6-Scripts/assets/55228336/078e4236-239b-400d-98df-4ecdaaea1acf)

**Comment by Zariaa27** [comment]
Using all default dvars and fresh install of Pluto T6, no scripts or nothing to conflict at all actually. Still does not work.

If there indeed is an error in my configuration, please go ahead and tell me so, as I'm not the one who Dev'd this script, I can't tell if it's bad or not.

Adding to this, I do not understand why I would launch it without any dvars, will this set them in my CFG for me?

**Comment by Resxt** [comment]
Yes like explained on the documentation, the script is made to set default values if you don't set a dvar.

If you simply install the 2 scripts it works out of the box.

I cannot help you more, you're not giving any useful info such as all scripts folder screenshots, cfg file and so on.

Again, I installed a clean copy of Plutonium, installed the server files, installed the mapvote files, tried a dedicated server in both mp and zm and it worked fine so I literally cannot reproduce your issue since it works fine

**Comment by Resxt** [comment]
I'm going to consider you solved it or moved on.
If you have another issue talk on the forum or on Discord
