### ISSUE TITLE
No commands are found after installation chat commands

### ISSUE THREAD

**Issue by Draakoor** [Resxt/Plutonium-T6-Scripts#5]
Hi there I installed chat commands like in the installation guide, but when I try !help I get no Commands found.
GSC-Tools is installed

**Comment by Resxt** [comment]
You don't have to "install" gsc-tool whatever this means since it's not something you can install anyways. Plutonium handles reading/compiling scripts automatically.

As for your issue, if I understand it correctly, then I'm gonna quote the README (which has a lot of instructions, which should answer most questions/prevent most issues)

> Also note that chat_commands.gsc doesn't provide any command on its own.
> You must install at least one command script to be able to use commands. Otherwise it will always say that you don't have any command.

If you did install one or several command files then this is very likely the port being wrong in the command files so edit the ports array in `chat_commands.gsc` and/or edit the ports being passed to CreateCommand in the command(s) file(s) you have
