### ISSUE TITLE
Game modes do not change

### ISSUE THREAD

**Issue by UnluckyKitty** [Resxt/Plutonium-T6-Scripts#7]
I was using mapvote on my server before the recent big client update and it worked perfectly. But after the update the game modes do not change. I reinstalled plutonium, did a clean install, including installing the server with new files and the problem was not solved. Maybe you know what the problem could be and can help solve it ?

**Comment by Resxt** [comment]
Hello @UnluckyKitty 

Thanks for reporting the issue.
I didn't think of updating my mapvote for the recent updates because I'm completely out of anything Plutonium.

The issue happens because T6 received massive changes when it comes to recipes/cfgs etc. and my mapvote didn't receive changes to adapt to these changes.
I just pushed an update that fixes the mode loading issue. I searched a bit and didn't find any other issue so everything should be fine.

Don't hesitate to report back any other issue you may have, everything looks good on my side.

Fixed in https://github.com/Resxt/Plutonium-T6-Scripts/commit/0f6a3761cc5c77f49872237c7cf2c91720c46f68

**Comment by UnluckyKitty** [comment]
I want to say that I just checked the new version and everything works fine again. All modes and maps are selected correctly again. Thank you very much for your prompt help.
